# Using BERT to classify the narrators (Multiclass Classification) [WIP:DRAFT]

In [1]:
%%capture

# make logs less verbose
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

# suppress UnparsedFlagAccessError warning
import sys
from absl import flags

sys.argv = ["preserve_unused_tokens=False"]
flags.FLAGS(sys.argv)

## Process data

In [2]:
import pandas as pd

df = pd.read_json("./data/jawbone.json")

Augment the data with the label (narrator).

In [3]:
import json

f = open("./data/unofficial_solution.json")
possible_solutions = json.load(f)
f.close()


def get_narrator(id):
    for key, ids in possible_solutions.items():
        if id in ids:
            return key
    return None


df["narrator"] = df["page"].apply(lambda x: get_narrator(x))
df

    page                                               text          narrator
0      1  I sit down alone at the appointed table and ta...        Bill Hardy
1      2  I plunged for the last time. The few remaining...       Oscar Mills
2      3  At my meeting with Clement yesterday, he had b...       John Walker
3      4  And I really think I would have preferred the ...        Bill Hardy
4      5  I hated my eye for being caught by what didn’t...     May Doncaster
..   ...                                                ...               ...
95    96  Now I think I will try a cup of what they inso...        Bill Hardy
96    97  To have slept and to wake right up surrounded ...       John Walker
97    98  He stood and looked down at me; but I was not ...  Sir Paul Trinder
98    99  And she wore a mauve love-knot on her breast, ...       Henry (dog)
99   100  I dimly guess why the old dead so wanted this....        Bill Hardy

[100 rows x 3 columns]

In [4]:
# tokenize paragraphs
import nltk
from nltk import sent_tokenize


def tokenize_sentences(paragraph):
    sentences = sent_tokenize(paragraph)

    valid_sentences = [
        sentence for sentence in sentences if any(c.isalnum() for c in sentence)
    ]
    return valid_sentences


df["text"] = df["text"].apply(tokenize_sentences)
df = df.explode("text").reset_index(drop=True)
df

      page                                               text    narrator
0        1  I sit down alone at the appointed table and ta...  Bill Hardy
1        1  Call me nervous, call me fey, if you will; at ...  Bill Hardy
2        1  It has not had much work since it flew so nimb...  Bill Hardy
3        1  As I watch the sea, Casy Ferris passes with do...  Bill Hardy
4        1                      Of course, to-day is the day.  Bill Hardy
...    ...                                                ...         ...
1225   100                                   O beastly woman.  Bill Hardy
1226   100  You know not how ill’s all here, about my hear...  Bill Hardy
1227   100  Henry, I feel it, is for the first and last ti...  Bill Hardy
1228   100                                   Good-bye, Henry.  Bill Hardy
1229   100                                      He drops awa.  Bill Hardy

[1230 rows x 3 columns]

In [5]:
from sklearn.model_selection import train_test_split

train_df, remaining_df = train_test_split(
    df, random_state=42, train_size=0.3, stratify=df.narrator.values
)
test_df, _ = train_test_split(
    remaining_df, random_state=42, train_size=0.1, stratify=remaining_df.narrator.values
)
print(train_df.shape)
print(test_df.shape)

(369, 3)
(86, 3)

In [6]:
from sklearn import preprocessing
from keras.utils import to_categorical

# labels (narrators) as categorical variable
label = preprocessing.LabelEncoder()
y_train = to_categorical(label.fit_transform(train_df["narrator"]))
y_test = to_categorical(label.fit_transform(test_df["narrator"]))

In [7]:
import tensorflow_hub as hub

bert_layer = hub.KerasLayer(
    "https://tfhub.dev/tensorflow/bert_en_cased_L-12_H-768_A-12/2", trainable=True
)

In [8]:
from bert import tokenization
import numpy as np

vocab_file = bert_layer.resolved_object.vocab_file.asset_path.numpy()
do_lower_case = bert_layer.resolved_object.do_lower_case.numpy()
tokenizer = tokenization.FullTokenizer(vocab_file, do_lower_case)


# from https://www.kaggle.com/code/nayansakhiya/text-classification-using-bert
def bert_encode(texts, tokenizer, max_len=512):
    all_tokens = []
    all_masks = []
    all_segments = []

    for text in texts:
        text = tokenizer.tokenize(text)

        text = text[: max_len - 2]
        input_sequence = ["[CLS]"] + text + ["[SEP]"]
        pad_len = max_len - len(input_sequence)

        tokens = tokenizer.convert_tokens_to_ids(input_sequence) + [0] * pad_len
        pad_masks = [1] * len(input_sequence) + [0] * pad_len
        segment_ids = [0] * max_len

        all_tokens.append(tokens)
        all_masks.append(pad_masks)
        all_segments.append(segment_ids)

    return np.array(all_tokens), np.array(all_masks), np.array(all_segments)

In [9]:
import tensorflow as tf


# adapted from https://www.kaggle.com/code/nayansakhiya/text-classification-using-bert
# TODO: improve
def build_model(bert_layer, max_len=512):
    input_word_ids = tf.keras.Input(
        shape=(max_len,), dtype=tf.int32, name="input_word_ids"
    )
    input_mask = tf.keras.Input(shape=(max_len,), dtype=tf.int32, name="input_mask")
    segment_ids = tf.keras.Input(shape=(max_len,), dtype=tf.int32, name="segment_ids")

    pooled_output, sequence_output = bert_layer(
        [input_word_ids, input_mask, segment_ids]
    )

    clf_output = sequence_output[:, 0, :]

    lay = tf.keras.layers.Dense(64, activation="relu")(clf_output)
    lay = tf.keras.layers.Dropout(0.2)(lay)
    lay = tf.keras.layers.Dense(32, activation="relu")(lay)
    lay = tf.keras.layers.Dropout(0.2)(lay)
    out = tf.keras.layers.Dense(8, activation="softmax")(lay)  # 8 labels-narrators

    model = tf.keras.models.Model(
        inputs=[input_word_ids, input_mask, segment_ids], outputs=out
    )
    model.compile(
        optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"]
    )

    return model

In [10]:
X_train = bert_encode(train_df.text.values, tokenizer)
X_test = bert_encode(test_df.text.values, tokenizer)

In [11]:
model = build_model(bert_layer)
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_word_ids (InputLayer  [(None, 512)]                0         []
 )

 input_mask (InputLayer)     [(None, 512)]                0         []

 segment_ids (InputLayer)    [(None, 512)]                0         []

 keras_layer (KerasLayer)    [(None, 768),                1083102   ['input_word_ids[0][0]',
                              (None, 512, 768)]           73         'input_mask[0][0]',
                                                                     'segment_ids[0][0]']

 tf.__operators__.getitem (  (None, 768)                  0         ['keras_layer[0][1]']
 SlicingOpLambda)

 dense (Dense)               (None, 64)                   49216     ['tf.__operators__.getitem[0][
                                                                    0]']

 dropout (Dropout)           (None, 64)                   0         ['dense[0][0]']

 dense_1 (Dense)             (None, 32)                   2080      ['dropout[0][0]']

 dropout_1 (Dropout)         (None, 32)                   0         ['dense_1[0][0]']

 dense_2 (Dense)             (None, 8)                    264       ['dropout_1[0][0]']

==================================================================================================
Total params: 108361833 (413.37 MB)
Trainable params: 108361832 (413.37 MB)
Non-trainable params: 1 (1.00 Byte)
__________________________________________________________________________________________________

In [12]:
model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=1,
    batch_size=10,
    verbose=1,
)

37/37 [==============================] - 588s 16s/step - loss: 2.3057 - accuracy: 0.1301 - val_loss: 2.0799 - val_accuracy: 0.1512

(WIP)